Use data from `rime-dict-source`
nk2028/ToMiddleChinese pull request #3
Opened 2023-01-06 06:45 UTC by graphemecluster

2023-01-06 06:54 UTC, graphemecluster commented
其實用結巴分詞的話諸如「新年進步」之類會被分成兩個詞的詞條都是沒用的，可以刪除

2023-01-06 06:58 UTC, syimyuzya commented
話說「qimyonhmieuzsjyt」是什麼？🤔

【PS 其實我看得懂，但是我拒絕看懂（

2023-01-06 07:47 UTC, bennettphon commented
> 話說「qimyonhmieuzsjyt」是什麼？🤔
> 
> 【PS 其實我看得懂，但是我拒絕看懂（

音韻描述啊。。polyhedron的音標一用就是１０年。。

2023-01-06 09:05 UTC, syimyuzya commented
> > 話說「qimyonhmieuzsjyt」是什麼？thinking
> > 【PS 其實我看得懂，但是我拒絕看懂（
> 
> 音韻描述啊。。polyhedron的音標一用就是１０年。。

道理我懂，「音韻描述」不是 qyim-uinh-myew-zjwit 麼（

2023-01-06 09:11 UTC, syimyuzya requested changes
nk2028 從 2022 年春季以來已經早已採用[切韻拼音](https://phesoca.com/tshet/)作為統一轉寫，僅有過去曾轉寫過的文字可以例外。

現在這都 2023 了……簡直讓人覺得這項目是穿越來的（（

2023-01-06 09:19 UTC, graphemecluster commented
@syimyuzya 切韻拼音我在上一個 PR #2 已經加了（實際上，在下述的 translator bot 添加切韻拼音纔是我把兩年沒碰的這個的 repo 找出來改的原因），本來綾香已經打算 release 了，但有些詞條出了些問題，因此我纔把來源換成 rime-dict-source 的
我覺得古韻羅馬字可以暫且先保留，待正式版再刪除吧，因為綾香的 https://github.com/ayaka14732/telegram-translate-bot 現在 depends on 這個 package

2023-01-06 09:34 UTC, syimyuzya commented
> @syimyuzya 切韻拼音我在上一個 PR #2 已經加了（實際上，在下述的 translator bot 添加切韻拼音纔是我把兩年沒碰的這個的 repo 找出來改的原因），本來綾香已經打算 release 了，但有些詞條出了些問題，因此我纔把來源換成 rime-dict-source 的 我覺得古韻羅馬字可以暫且先保留，待正式版再刪除吧，因為綾香的 https://github.com/ayaka14732/telegram-translate-bot 現在 depends on 這個 package

啊，我指的是代碼裡面出現的「音韻描述」的那個轉寫😂 而對方案的支援是沒有問題的w

2023-01-06 09:58 UTC, graphemecluster commented
完全に理解した
是我在 #2 之前閲讀代碼時搞錯了點東西，導致我把 to音韻描述 和 to_kyonh 的輸出結果弄成一樣，然後以為沒分別就刪掉了（🌿
我稍後加回順便改名叫 description

2023-01-06 11:05 UTC, ayaka14732 commented
如果程式語言支援漢字的話，變數名稱寫成漢字比較好 😆

2023-01-07 03:23 UTC, syimyuzya reviewed
好耶w

【approval 的話，我先稍微檢查點切拼細節w

2023-01-07 03:45 UTC, syimyuzya approved these changes

2023-01-07 05:27 UTC, graphemecluster commented
@ayaka14732 看看沒有問題就由你來 merge 一下

2023-01-07 05:29 UTC, ayaka14732 approved these changes

2023-01-07 05:30 UTC, merged

2023-01-08 10:37 UTC, graphemecluster commented
@ayaka14732 你睇下重新發佈 0.2.0 定點，順便睇埋 https://github.com/nk2028/to-middle-chinese

2023-01-09 03:33 UTC, ayaka14732 commented
@graphemecluster 我覺得可以重新發佈 0.2.0

2023-01-09 07:03 UTC, graphemecluster commented
@ayaka14732 我刪咗個舊 release 喇，你重新 release 一次

2023-01-09 14:01 UTC, ayaka14732 commented
> @ayaka14732 我刪咗個舊 release 喇，你重新 release 一次

done